version: '3'
services:
  db1:
    image: mysql:8
    container_name: mysql-db1
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    expose:
      # Opers port 3306 on the container
      - '3306'
    environment:
      MYSQL_DATABASE: records
      MYSQL_USER: testuser
      MYSQL_PASSWORD: senha
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf

  db2:
    image: mysql:8
    container_name: sdb
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    expose:
      # Opers port 3306 on the container
      - "3306"
    environment:
      MYSQL_DATABASE: records
      MYSQL_USER: testuser
      MYSQL_PASSWORD: senha
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./slave-data:/var/lib/mysql
      - ./slave-config/my.cnf:/etc/my.cnf
