version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:8080
      - 4020:4020
    depends_on:
      - bdm1
      - bdm2
      - bdm3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - blcnetwork

  bdm1:
    container_name: bdm1
    image: mariadb
    ports:
      - 33061:3306
    environment:
       MYSQL_ROOT_PASSWORD: "senha"
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#      - MYSQL_DATABASE=your_database
#    volumes:
#      - .db1_data:/var/lib/mysql
#      - ./galera/db1:/etc/mysql/conf.d
#    command: ["--wsrep-new-cluster"]
    networks:
      - blcnetwork

  bdm2:
    container_name: bdm2
    image: mariadb
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: "senha"
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#      - MYSQL_DATABASE=your_database
#    volumes:
#      - .db2_data:/var/lib/mysql
#      - ./galera/db2:/etc/mysql/conf.d
    networks:
      - blcnetwork

  bdm3:
    container_name: bdm3
    image: mariadb
    ports:
      - 33063:3306
    environment:
       MYSQL_ROOT_PASSWORD: "senha"
 #     - MYSQL_USER=user
 #     - MYSQL_PASSWORD=password
 #     - MYSQL_DATABASE=your_database
#    volumes:
#      - .db3_data:/var/lib/mysql
#      - ./galera/db3:/etc/mysql/conf.d
    networks:
      - blcnetwork

networks:
  blcnetwork:
    name: blcnetwork

