version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 8080:8080
      - 4020:4020
    depends_on:
      - bdm1
      - bdm2
      - bdm3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  bdm1:
    container_name: bdm1
    image: mariadb
    environment:
       MYSQL_ROOT_PASSWORD: "senha"
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#      - MYSQL_DATABASE=your_database
    volumes:
      - .db1_data:/var/lib/mysql
      - ./galera/db1:/etc/mysql/conf.d
    command: ["--wsrep-new-cluster"]

  bdm2:
    container_name: bdm2
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "senha"
#      - MYSQL_USER=user
#      - MYSQL_PASSWORD=password
#      - MYSQL_DATABASE=your_database
    volumes:
      - .db2_data:/var/lib/mysql
      - ./galera/db2:/etc/mysql/conf.d

  bdm3:
    container_name: bdm3
    image: mariadb
    environment:
       MYSQL_ROOT_PASSWORD: "senha"
 #     - MYSQL_USER=user
 #     - MYSQL_PASSWORD=password
 #     - MYSQL_DATABASE=your_database
    volumes:
      - .db3_data:/var/lib/mysql
      - ./galera/db3:/etc/mysql/conf.d

